# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set node version
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # install devs
      - name: Install Dependencies
        run: npm ci

      # run linting
      - name: Run Linting
        run: npm run lint:fix

        # # run testing
        # - name: Run test
        #   run: npm run test

        # - name: Upload Test Report
        #   uses: actions/upload-artifact@v1
        #   with:
        #     name: report
        #     path: report.json

        env:
          CI: true
